### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by EazyFTW** [FearGames/CommonUtilities#1]
```[06:57:01 INFO]: [CommonUtilities] Enabling CommonUtilities v2.1.1-SNAPSHOT
[06:57:01 ERROR]: Error occurred while enabling CommonUtilities v2.1.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at it.feargames.commonutilities.CommonUtilities.onEnable(CommonUtilities.java:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:576) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:433) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784) ~[patched_1.13.1.jar:git-Paper-221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[06:57:01 INFO]: [CommonUtilities] Disabling CommonUtilities v2.1.1-SNAPSHOT
[06:57:01 ERROR]: Error occurred while disabling CommonUtilities v2.1.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at it.feargames.commonutilities.CommonUtilities.onDisable(CommonUtilities.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:576) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:433) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784) ~[patched_1.13.1.jar:git-Paper-221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]```

**Comment by sgdc3** [comment]
What's your server version?

**Comment by EazyFTW** [comment]
> What's your server version?

1.13.1 (Paper)

**Comment by sgdc3** [comment]
Ok i was able to reproduce the issue, i'll try to fix it tomorrow :)

**Comment by EazyFTW** [comment]
> Ok i was able to reproduce the issue, i'll try to fix it tomorrow :)

Thanks a bunch!

**Comment by sgdc3** [comment]
@EazyFTW Fixed, please test ;)

**Comment by sgdc3** [comment]
https://ci.codemc.org/job/FearGames/job/CommonUtilities/

**Comment by EazyFTW** [comment]
> https://ci.codemc.org/job/FearGames/job/CommonUtilities/

Works, it would be nice if you could possibly fix the title, it has the color code values in it. (If you can fix it).

https://i.eazyftw.com/2OnKPwt

Thanks!

I'm using this for the scoreboard on <1.13.x, thanks!

**Comment by sgdc3** [comment]
@EazyFTW That's very strange but the image link seems broken, could you update it please? :/

**Comment by EazyFTW** [comment]
> @EazyFTW That's very strange but the image link seems broken, could you update it please? :/

Yea, sorry, my friend made it (the image site) and he's updating it, here try this: https://i.eazyftw.com/files/2OnKPwt.mp4

**Edit:** The other one now works :p

**Comment by sgdc3** [comment]
hmm that is strange, is it featherboard?

**Comment by EazyFTW** [comment]
> hmm that is strange, is it featherboard?

KiteBoard.

**Comment by sgdc3** [comment]
I tested it only with featherboard, sorry, could you open a new ticket flr this issue?
